[package]
name = "orde-rs"
version = "0.1.0"
authors = ["Aleksey Kliger <aleksey@lambdageek.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[features]

# Define "not implemented" errors
has_unimpl = []